-- IMAP inbox: track direction (outbound vs inbound) and the headers needed to
-- thread an inbound reply back to the outbound message it answers.
--
-- direction    'outbound' for emails we send via the SMTP sidecar, 'inbound' for
--              replies pulled in by the IMAP sidecar. All existing rows backfill
--              to 'outbound' (everything we have today is something HR sent).
-- message_id   RFC-822 Message-ID generated by the SMTP sidecar before send and
--              persisted on the outbound row. Lets us thread replies.
-- in_reply_to  The In-Reply-To header from an inbound message — should match a
--              prior outbound row's message_id so we can attach it to the same
--              candidate / job opening.
--
-- Note on recipient_email semantics: the column is reused as "the other party"
-- regardless of direction. For outbound = HR's recipient. For inbound = the HM /
-- candidate who sent the reply. Avoids adding a redundant sender_email column.

ALTER TABLE email_log
    ADD COLUMN IF NOT EXISTS direction TEXT NOT NULL DEFAULT 'outbound'
        CHECK (direction IN ('outbound', 'inbound'));

ALTER TABLE email_log ADD COLUMN IF NOT EXISTS message_id TEXT;
ALTER TABLE email_log ADD COLUMN IF NOT EXISTS in_reply_to TEXT;

-- Inbound matching looks up the parent outbound row via message_id = in_reply_to,
-- so an index on each side keeps that lookup O(log n).
CREATE INDEX IF NOT EXISTS idx_email_log_message_id ON email_log (message_id);
CREATE INDEX IF NOT EXISTS idx_email_log_in_reply_to ON email_log (in_reply_to);
